services:
  - type: web
    name: heart-disease-ml-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "./startup.sh"
    plan: free
    
    # Environment variables
    envVars:
      - key: MONGODB_CONNECTION_STRING
        sync: false  # Set this in Render dashboard
      - key: MONGODB_DATABASE_NAME
        value: healthcare
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000  # Render uses port 10000
      - key: MODEL_PATH
        value: models/heart_disease_model.pkl
      - key: MODEL_VERSION
        value: 1.0.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: API_WORKERS
        value: 1
    
    # Health check
    healthCheckPath: /api/v1/health
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Disk space for model files
    disk:
      name: heart-disease-models
      mountPath: /opt/render/project/src/models
      sizeGB: 1